language: rust
cache: cargo
rust:
  - stable
  - nightly
os:
  - linux
  - windows
  - osx
dist: focal
before_script:
  - rustup component add clippy
script:
  - cargo clippy -- -D warnings
  - cargo test